name: .NET Fake Continuous Deployment

x-test: &test
  name: Fake Deployment and Perf Testing
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        dotnet-quality: 'preview'
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y k6
    - name: Build docker stack and run perf tests
      run: docker-compose -f docker-compose-perf-test.yml up --always-recreate-deps --abort-on-container-exit --force-recreate --build perftests

x-env: &x-env
    API_TEST_CONNECTION_STRING: "http://orderbook:5237"
    MONGO_PW: ${MONGO_PASS}
    MONGO_USER: ${MONGO_USER}
    REDIS_PASSWORD: ${REDIS_PASSWORD}
    ENVIRONMENT: Development
    MONGO_HOST: mongo
    MONGO_PORT: 27017
    REDIS_HOST: redis
    REDIS_PORT: 6379


on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  
  add-order-perf-tes:
    <<: *test
    env:
      <<: *x-env
      TEST_FILE: add-order-test
    
  modify-order-perf-tes:
    <<: *test
    env:
      <<: *x-env
      TEST_FILE: modify-order-test

  get-price-perf-tes:
    <<: *test
    env:
      <<: *x-env
      TEST_FILE: add-order-test
        
  cycle-perf-tes:
    <<: *test
    env:
      <<: *x-env
      TEST_FILE: cycle-test
      
