name: .NET Continuous Integration

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          dotnet-quality: 'preview'
      - name: Run unit tests
        run: dotnet test --logger GitHubActions ./src/backend/OrderBookService.UnitTests/OrderBookService.UnitTests.csproj
        
  integration-tests:
    name: Api Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          dotnet-quality: 'preview'
      - name: Run API tests
        run: dotnet test --logger GitHubActions ./src/backend/OrderBookService.IntegrationTests/OrderBookService.IntegrationTests.csproj

  api-tests:     
    name: Api Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          dotnet-quality: 'preview'
      - name: Build docker stack
        run: docker-compose up -d --force-recreate --build -f docker-compose-dev.yml
      - name: Run API tests
        run: dotnet test --logger GitHubActions ./src/backend/OrderBookService.ApiTests/OrderBookService.ApiTests.csproj
